"li t0, 0\n\t"
"li t2, 8\n\t"
"OutLoop:\n\t"
"li t1, 0\n\t"
"bge t0, t2, END\n\t"
"addi %[p_x], %[p_x], 2\n\t"
"lw %[p_tmp1], 0(%[p_x])\n\t"
"bnez %[flag], END\n\t"
"InsideLoop:\n\t"
"bge t1, t2, OutLoop\n\t"
"slli t3, t1, 1\n\t"
"add t4, %[p_x], t3\n\t"
"lw x18, 0(t4)\n\t" 			
"add x19, x18, %[p_tmp1]\n\t"
"lw %[p_tmp2], 0(%[target])\n\t"
"beq x19, %[p_tmp2], GetFlag\n\t"
"slli t1, t1, 1\n\t"
"j InsideLoop\n\t"
"GetFlag:\n\t"
"addi %[flag], %[flag], 1\n\t"
"slli t0, t0, 1\n\t"
"j OutLoop\n\t"
"END:\n\t"
