"li t1, 8\n\t"
"vsetvli t1, t0, e16, ta, ma\n\t"
"Loop:\n\t"
"vle16.v v0, (%[p_x])\n\t"
"vadd.vx v1, v0, %[p_x]\n\t"
"sub t1, t1, t0\n\t"
"slli t0, t0, 1\n\t"
"vmseq.vx v2, v1, %[target]\n\t"
"vfirst.m %[p_tmp1], v2\n\t"
"bge %[p_tmp1], x0, GetFlag\n\t"
"bnez t1, Loop\n\t"
"GetFlag:\n\t"
"addi %[flag], %[flag], 1\n\t"

