"li t0, 0\n\t"
"li t2, 8\n\t"
"OuterLoop:\n\t"
"li t1, 0\n\t"
"bge t0, t2, END\n\t"
//"li %[flag], 0\n\t" 
//"add %[p_tmp1], x0, %[p_x]\n\t"
"InnerLoop:\n\t"
//"lw x18, 0(%[p_x])\n\t"
"lw %[p_tmp2], 0(%[target])\n\t"
//"add x19, x18, %[p_tmp1]\n\t"
//"beq x19, %[p_tmp2], GetFlag\n\t"
//"addi %[p_x], %[p_x], 2\n\t"
"addi t1, t1, 1\n\t"
"bge t1, t2, EndInnerLoop\n\t"
"beq x0, x0, InnerLoop\n\t"
//"GetFlag:\n\t"
//"addi %[flag], %[flag], 1\n\t"
"EndInnerLoop:\n\t"
"addi t0, t0, 1\n\t"
"beq x0, x0, OuterLoop\n\t"
"END:\n\t"
